### ISSUE TITLE
Add SCP-079 Example

### ISSUE THREAD

**Issue by Setnour6** [getmyisland/scp-observer-modding#2]
### Are you willing to contribute to this change?
Maybe

### What is the feature you are presenting?
I would like to see an example of a modded SCP-079 in this repository so everyone can better understand the changes of SCP-079, including proper documentation of how it can and must be done.
Right now, I had difficulty fully understanding the instructions when it comes to modding SCP-079. I didn't know that the folder next to `mod.json` needed to have the same name as `"mod": "yourmodname",` (i.e. folder named yourmodname) (I spent a whole hour trying to figure that out).

### Are there alternatives to your proposal?
You can add a note saying that the folder next to mod.json must match the same name given in the `"mod":` line

**Comment by getmyisland** [comment]
Thank you for the feedback, I will improve the documentation. For now here is a better explanation specifically for SCP-079 mods. Any macro like this `%NAME%` must be replaced with your specific name.

- %MOD%FOLDER%
  - mod.json
  - %MOD%
    - image.jpg
    - random.png
    - hello_world.jpg

**%MOD%FOLDER%** is the folder that contains your mod. Can have any name.
**%MOD%** is in this case the folder that contains all images for SCP-079. Can have any name but must be referenced in the `mod.json` like this `"mod": "%MOD%",`

This structure stays the same for all mods currently. The only thing that changes is the `%MOD%` part. For other SCPs you would have a single AssetBundle file instead.
